# Generated by Django 5.2.17 on 2026-09-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('course', models.CharField(max_length=80)),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('project', 'Project'), ('reading', 'Reading'), ('other', 'Other')], default='assignment', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('estimated_minutes', models.PositiveIntegerField(default=60)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completed', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('practice', 'Practice'), ('game', 'Game'), ('workout', 'Workout'), ('meeting', 'Team meeting'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('repeat_weekly', models.BooleanField(default=False)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='planner.academictask')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
