# Generated by Django 5.2.17 on 2026-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='weekdays',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
