# Generated by Django 5.2.17 on 2026-09-22 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_event_weekdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('weekdays', models.CharField(default='0,1,2,3,4,5,6', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planner.flexibleroutine')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('routine', 'date'), name='one_routine_session_per_day')],
            },
        ),
    ]
